# Eerste request: toevoegen van een nieuw record zonder aangemelde gebruiker
POST https://localhost:7101/api/Sets
Content-Type: application/json
Accept: application/json

{
  "name": "New Set 2",
  "code": "NS2",
  "releaseDate": "2023-01-01"
}

###

# Tweede request: toevoegen van een nieuw record als aangemelde gebruiker
# @no-redirect
# @no-cookie-jar
POST https://localhost:7101/api/Sets
Content-Type: application/json
Accept: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8H9KMD2CQ61Gtuxgcoy7Jc3h_yWXu_nXvFemKY0pENhN4-gue6q4a91TfOQR0Vm349CKUNxLUpwKY7myGpj-UOxJzme3bA0Ay_VhyEvvayN1DGBPTHQyRC2Y11GZ91_Vy6GLb1Z1NsDm_wWqcV61bI38VlAw-S8O-mfmaZg9R7Uh9W-Lg_qeBxU4qFI35nhPJ1283FuGUhkIfFiSyATt3LpWJEBCEiBD6yD6lnBQQfZsL6zjAQqTQc9xoWek1BIjI1bpMp0YlHo7Qgl5_0ib-8JTGlsq23nU0QzWWxfVxa9LwRlFv6yzh_ndCFSHHG7oEUT0wWTgwX1vr_1L1mrPkyX8pxoIhwYqsdCa1iml8SBsOkEqJDZ7lrfrCDvv1wTv-8d7JbzvzzoB0qbX9wFCDFmI4cRrtnEDGwYCuAvnWrJ2uN_VkyyT-jXveL3kGeTYiXk_47n-drtkK8m0UvMNztZHpI8GBuK8gqOeKfYdtJQLNAz8MsstUpZBkgS4N-YSHbOABHwKYHNGVZ1CP9wEmmPflCXEk0twcuAli94v_xSxKuulQOdI3YZDud5pyf9IiK8-WuwPA6iD1Dar5O1DJ24UzffntmOk5NeJsM_wXLzl7hEOUSQA3Q-fOqweLG2PPW_RhK2LHYzKvNL7y4l3SyeP-A98qDB8Sf1LTc5EVBINJ9_oLwKFVeV5N7zjto7hWN0NbCYdCadgd1TqVs5_oJV2jthUYf7zfqL-NTD7vlO_UIZJgFQl2Rjd3Ox3YVyMlb-Q0t2PqyScW57vOAUl2UA4YF2EjRqyYvmNSK-HBgo2kemB362ozzYzP9vVWoyHvw

{
  "name": "New Set 2",
  "code": "NS2",
  "releaseDate": "2023-01-01"
}

