image: mcr.microsoft.com/dotnet/sdk:latest

variables:
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/'

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
    - '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
    - '$NUGET_PACKAGES_DIRECTORY'
  policy: pull-push

before_script:
  - 'dotnet restore --packages $NUGET_PACKAGES_DIRECTORY'
  
build:
  stage: build
  script:
    - 'dotnet build --no-restore'

tests:
  stage: test
  script:
    - 'dotnet test --no-restore --collect:"XPlat Code Coverage" --logger junit'
    - 'dotnet tool install dotnet-reportgenerator-globaltool
      --tool-path tools --version 5.2.3'
    - './tools/reportgenerator
      -reports:"Tests/TestResults/*/coverage.cobertura.xml"
      -targetdir:"coveragereport" -reporttypes:Html'
  artifacts:
    when: always
    reports:
      junit: Tests/TestResults/TestResults.xml
    paths:
      - coveragereport
