@startuml
!include .\\BL\IManager.puml
!include .\\BL\Manager.puml
!include .\\DAL\InMemoryRepository.puml
!include .\\DAL\IRepository.puml
!include .\\Domain\Card.puml
!include .\\Domain\CardAbility.puml
!include .\\Domain\CardColour.puml
!include .\\Domain\CardType.puml
!include .\\Domain\Deck.puml
!include .\\Domain\DeckEntry.puml
!include .\\Domain\Set.puml
!include .\\Domain\SetEntry.puml
!include .\\UI-CA\ConsoleUi.puml
!include .\\UI-CA\Program.puml
!include .\\UI-MVC\Program.puml
!include .\\DAL\EF\DataSeeder.puml
!include .\\DAL\EF\MTGMDbContext.puml
!include .\\DAL\EF\Repository.puml
!include .\\UI-CA\Extensions\CardExtentions.puml
!include .\\UI-CA\Extensions\DeckExtentions.puml
!include .\\UI-CA\Extensions\SetExtentions.puml
!include .\\UI-MVC\Controllers\CardController.puml
!include .\\UI-MVC\Controllers\DeckController.puml
!include .\\UI-MVC\Controllers\HomeController.puml
!include .\\UI-MVC\Controllers\SetController.puml
!include .\\UI-MVC\Models\ErrorViewModel.puml
!include .\\UI-MVC\Models\NewCardViewModel.puml
!include .\\UI-MVC\Controllers\Api\CardsController.puml
!include .\\UI-MVC\Controllers\Api\DeckEntriesController.puml
!include .\\UI-MVC\Controllers\Api\DecksController.puml
!include .\\UI-MVC\Controllers\Api\SetsController.puml
!include .\\UI-MVC\Models\Dto\CardDto.puml
!include .\\UI-MVC\Models\Dto\DeckEntryDto.puml
!include .\\UI-MVC\Models\Dto\NewDeckEntryDto.puml
!include .\\UI-MVC\Models\Dto\NewSetDto.puml
!include .\\UI-MVC\Models\Dto\SetDto.puml
!include .\\BL\obj\Debug\net70\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\BL\obj\Debug\net70\BL.AssemblyInfo.puml
!include .\\BL\obj\Debug\net70\BL.GlobalUsings.g.puml
!include .\\DAL\obj\Debug\net70\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\DAL\obj\Debug\net70\DAL.AssemblyInfo.puml
!include .\\DAL\obj\Debug\net70\DAL.GlobalUsings.g.puml
!include .\\Domain\obj\Debug\net70\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\Domain\obj\Debug\net70\Domain.AssemblyInfo.puml
!include .\\Domain\obj\Debug\net70\Domain.GlobalUsings.g.puml
!include .\\UI-CA\obj\Debug\net70\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\UI-CA\obj\Debug\net70\CA.AssemblyInfo.puml
!include .\\UI-CA\obj\Debug\net70\CA.GlobalUsings.g.puml
!include .\\UI-CA\obj\Debug\net70\UI-CA.AssemblyInfo.puml
!include .\\UI-CA\obj\Debug\net70\UI-CA.GlobalUsings.g.puml
!include .\\UI-MVC\obj\Debug\net70\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\UI-MVC\obj\Debug\net70\MTGM.UI.MVC.MvcApplicationPartsAssemblyInfo.puml
!include .\\UI-MVC\obj\Debug\net70\UI-MVC.AssemblyInfo.puml
!include .\\UI-MVC\obj\Debug\net70\UI-MVC.GlobalUsings.g.puml
!include .\\UI-MVC\obj\Debug\net70\UI-MVC.RazorAssemblyInfo.puml
!include .\\UI-MVC\Areas\Identity\Pages\Account\Login.cshtml.puml
!include .\\UI-MVC\Areas\Identity\Pages\Account\Logout.cshtml.puml
!include .\\UI-MVC\Areas\Identity\Pages\Account\Register.cshtml.puml
@enduml
