@startuml
class Set {
    + Set()
    + Set(name:String, code:String, releaseDate:DateTime, cards:List<SetEntry>)
    + Id : int <<get>> <<set>>
    + Name : string <<get>> <<set>>
}
class "ICollection`1"<T> {
}
Set --> "Code" String
Set --> "ReleaseDate" DateTime
Set --> "Cards<SetEntry>" "ICollection`1"
@enduml
